spring.application.name=USP SpaceHub
server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/usp_spacehub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Pacific/Fiji
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=SpaceHub@123

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Disable H2 Console
spring.h2.console.enabled=false

# Thymeleaf Configuration
spring.thymeleaf.cache=false

# Enable Hidden HTTP Methods
spring.mvc.hiddenmethod.filter.enabled=true

# Mail Configuration
app.mail.enabled=false